//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class level
    {
        
        public uint id;
        
        public uint sub_id;
        
        public System.Collections.Generic.List<uint> scene;
        
        public uint init_journey_difficulty;
        
        public bool time_scale_adjust;
        
        public object diy_obj;
    }
    
    public class levels
    {
        
        private static System.Collections.Generic.Dictionary<string, level> m_records;
        
        public static System.Collections.Generic.Dictionary<string, level> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, level>)Foundations.Excels.ExcelAnalyzer.init("level");
            }
        }
        
        public static bool TryGetValue(string key, out level record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("level", key, out record);
        }
    }
}
