//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class melee_logic
    {
        
        public uint logic_id;
        
        public int cd;
        
        public bool can_blaze;
        
        public System.ValueTuple<float, float> hit_period;
        
        public System.Nullable<System.ValueTuple<float, float>> hit_period_2;
        
        public float hit_box_offset;
        
        public float atk_part_speed;
        
        public int damage;
        
        public float knockback_ft;
    }
    
    public class melee_logics
    {
        
        private static System.Collections.Generic.Dictionary<string, melee_logic> m_records;
        
        public static System.Collections.Generic.Dictionary<string, melee_logic> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, melee_logic>)Foundations.Excels.ExcelAnalyzer.init("melee_logic");
            }
        }
        
        public static bool TryGetValue(string key, out melee_logic record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("melee_logic", key, out record);
        }
    }
}
