//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class monster
    {
        
        public uint id;
        
        public string name = "";
        
        public string sub_table_name = "";
        
        public string sub_table_key = "";
        
        public int hp;
        
        public int def;
        
        public float mass;
        
        public int basic_atk;
        
        public string monster_view = "";
        
        public string monster_behaviour_tree = "";
        
        public int fire_logic;
        
        public float feedback;
        
        public System.Collections.Generic.Dictionary<uint, float> loot_list;
        
        public System.Collections.Generic.List<string> death_vfx;
        
        public System.Collections.Generic.List<uint> component;
        
        public System.Collections.Generic.Dictionary<string, int> sub_monsters;
    }
    
    public class monsters
    {
        
        private static System.Collections.Generic.Dictionary<string, monster> m_records;
        
        public static System.Collections.Generic.Dictionary<string, monster> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, monster>)Foundations.Excels.ExcelAnalyzer.init("monster");
            }
        }
        
        public static bool TryGetValue(string key, out monster record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("monster", key, out record);
        }
    }
}
