//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class monster_group
    {
        
        public uint id;
        
        public uint sub_id;
        
        public uint monster_id;
        
        public string init_state = "";
        
        public UnityEngine.Vector2 pos;
        
        public int count_max;
        
        public int tension_min;
        
        public int tension_max;
        
        public float k_distance;
        
        public float k_time;
        
        public float kill_pressure;
        
        public int tide_count_addtion;
        
        public float tide_time_addtion;
    }
    
    public class monster_groups
    {
        
        private static System.Collections.Generic.Dictionary<string, monster_group> m_records;
        
        public static System.Collections.Generic.Dictionary<string, monster_group> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, monster_group>)Foundations.Excels.ExcelAnalyzer.init("monster_group");
            }
        }
        
        public static bool TryGetValue(string key, out monster_group record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("monster_group", key, out record);
        }
    }
}
