//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class role
    {
        
        public uint id;
        
        public string portrait = "";
    }
    
    public class roles
    {
        
        private static System.Collections.Generic.Dictionary<string, role> m_records;
        
        public static System.Collections.Generic.Dictionary<string, role> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, role>)Foundations.Excels.ExcelAnalyzer.init("role");
            }
        }
        
        public static bool TryGetValue(string key, out role record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("role", key, out record);
        }
    }
}
