//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class scene
    {
        
        public uint id;
        
        public string name = "";
        
        public uint scene_resource;
        
        public System.Collections.Generic.List<System.ValueTuple<uint, float, float, float>> scene_road;
        
        public uint scene_plot;
        
        public uint scene_monster_group;
        
        public System.Nullable<float> water_height;
        
        public string scene_water_view = "";
        
        public string vfx_environment = "";
        
        public string scene_initial_resource = "";
        
        public object diy_obj;
    }
    
    public class scenes
    {
        
        private static System.Collections.Generic.Dictionary<string, scene> m_records;
        
        public static System.Collections.Generic.Dictionary<string, scene> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, scene>)Foundations.Excels.ExcelAnalyzer.init("scene");
            }
        }
        
        public static bool TryGetValue(string key, out scene record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("scene", key, out record);
        }
    }
}
