//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class shield_logic
    {
        
        public uint logic_id;
        
        public int cd;
        
        public bool can_blaze;
        
        public System.ValueTuple<float, float> hit_period;
        
        public float def_range;
        
        public float hit_box_offset;
        
        public float atk_part_speed;
        
        public int damage;
        
        public float knockback_ft;
        
        public object diy_obj;
    }
    
    public class shield_logics
    {
        
        private static System.Collections.Generic.Dictionary<string, shield_logic> m_records;
        
        public static System.Collections.Generic.Dictionary<string, shield_logic> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, shield_logic>)Foundations.Excels.ExcelAnalyzer.init("shield_logic");
            }
        }
        
        public static bool TryGetValue(string key, out shield_logic record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("shield_logic", key, out record);
        }
    }
}
