//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class work
    {
        
        public uint job_id;
        
        public string name = "";
        
        public uint cubicle_count;
        
        public float job_amount;
        
        public string job_class = "";
    }
    
    public class works
    {
        
        private static System.Collections.Generic.Dictionary<string, work> m_records;
        
        public static System.Collections.Generic.Dictionary<string, work> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, work>)Foundations.Excels.ExcelAnalyzer.init("work");
            }
        }
        
        public static bool TryGetValue(string key, out work record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("work", key, out record);
        }
    }
}
