//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Resources_moved/input/Control_1.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Control_1: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Control_1()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Control_1"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""6217da5f-2eb7-40aa-9dd1-baf2e8660619"",
            ""actions"": [
                {
                    ""name"": ""SelectCharacter_1"",
                    ""type"": ""Button"",
                    ""id"": ""b4a4d034-e08c-4717-a199-679c9f4a8c0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCharacter_2"",
                    ""type"": ""Button"",
                    ""id"": ""fb7a5e56-9a44-41e5-80a8-2eef1e78573f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCharacter_3"",
                    ""type"": ""Button"",
                    ""id"": ""49923390-392e-48fe-bd26-cd4b3a4b0d55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCharacter_4"",
                    ""type"": ""Button"",
                    ""id"": ""5a9fac5d-4b4e-4805-8e1e-773724ce5005"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""4ef82538-c8d0-400b-94ff-ea6f4f254200"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1.401298E-45)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""2a1d6209-5a45-4981-9d81-d2325e7fca35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=1.401298E-45,pressPoint=1.401298E-45),Hold(duration=1.401298E-45,pressPoint=1.401298E-45)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""a6c49c65-0c81-4076-8b21-1960d99290ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Del"",
                    ""type"": ""Button"",
                    ""id"": ""50935d2f-9ab5-47c6-bbc8-3d0c3112e793"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PullUp"",
                    ""type"": ""Button"",
                    ""id"": ""3b885522-ce36-4b1e-b939-12c0d19e6ed5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=1.401298E-45,pressPoint=1.401298E-45),Hold(duration=1.401298E-45,pressPoint=1.401298E-45)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PullDown"",
                    ""type"": ""Button"",
                    ""id"": ""77996616-8e47-441d-ad68-9df36ffeab28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=1.401298E-45,pressPoint=1.401298E-45),Hold(duration=1.401298E-45,pressPoint=1.401298E-45)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""41b07fe5-1d50-46fd-8975-09a3b9254c7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Load"",
                    ""type"": ""Button"",
                    ""id"": ""6ecf78aa-1475-443e-b034-986225e03c2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PushCar"",
                    ""type"": ""Button"",
                    ""id"": ""ef381eec-6204-4e8b-aada-eac017fe5ed0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""592f2b1c-0e94-46a8-9317-98644d0cf52c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCharacter_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""683f528e-81c3-4710-b676-a1e091a1fd2a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCharacter_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f8d2f8a-90d2-4ccb-a4a7-de10b940c62d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCharacter_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b986f1b-db6a-44de-a5e9-71abf4af6f2b"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCharacter_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c93cb74-1524-481c-a7ac-5a5b2ecff051"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bee15867-b59a-4e45-84fc-b3e51a811d3e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cba8447-cca6-4cc9-bd4b-f81aa68ff2e8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0ef05c3-1c48-4d67-b9ff-0e97e3ab2cce"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Del"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44e5ebb6-3ad5-40cf-901c-961bd45d9d47"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e9e846a-1046-4b4f-839e-3907a3d97163"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""691104fa-aa57-46be-883a-a6726107cfed"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da947b96-edc8-4e40-aaab-946f86b60f3b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press(pressPoint=1.401298E-45)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Load"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6c16373-c3bc-492c-b574-7db1cb5e3df7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_SelectCharacter_1 = m_GamePlay.FindAction("SelectCharacter_1", throwIfNotFound: true);
        m_GamePlay_SelectCharacter_2 = m_GamePlay.FindAction("SelectCharacter_2", throwIfNotFound: true);
        m_GamePlay_SelectCharacter_3 = m_GamePlay.FindAction("SelectCharacter_3", throwIfNotFound: true);
        m_GamePlay_SelectCharacter_4 = m_GamePlay.FindAction("SelectCharacter_4", throwIfNotFound: true);
        m_GamePlay_RightClick = m_GamePlay.FindAction("RightClick", throwIfNotFound: true);
        m_GamePlay_LeftClick = m_GamePlay.FindAction("LeftClick", throwIfNotFound: true);
        m_GamePlay_Esc = m_GamePlay.FindAction("Esc", throwIfNotFound: true);
        m_GamePlay_Del = m_GamePlay.FindAction("Del", throwIfNotFound: true);
        m_GamePlay_PullUp = m_GamePlay.FindAction("PullUp", throwIfNotFound: true);
        m_GamePlay_PullDown = m_GamePlay.FindAction("PullDown", throwIfNotFound: true);
        m_GamePlay_Brake = m_GamePlay.FindAction("Brake", throwIfNotFound: true);
        m_GamePlay_Load = m_GamePlay.FindAction("Load", throwIfNotFound: true);
        m_GamePlay_PushCar = m_GamePlay.FindAction("PushCar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private List<IGamePlayActions> m_GamePlayActionsCallbackInterfaces = new List<IGamePlayActions>();
    private readonly InputAction m_GamePlay_SelectCharacter_1;
    private readonly InputAction m_GamePlay_SelectCharacter_2;
    private readonly InputAction m_GamePlay_SelectCharacter_3;
    private readonly InputAction m_GamePlay_SelectCharacter_4;
    private readonly InputAction m_GamePlay_RightClick;
    private readonly InputAction m_GamePlay_LeftClick;
    private readonly InputAction m_GamePlay_Esc;
    private readonly InputAction m_GamePlay_Del;
    private readonly InputAction m_GamePlay_PullUp;
    private readonly InputAction m_GamePlay_PullDown;
    private readonly InputAction m_GamePlay_Brake;
    private readonly InputAction m_GamePlay_Load;
    private readonly InputAction m_GamePlay_PushCar;
    public struct GamePlayActions
    {
        private @Control_1 m_Wrapper;
        public GamePlayActions(@Control_1 wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectCharacter_1 => m_Wrapper.m_GamePlay_SelectCharacter_1;
        public InputAction @SelectCharacter_2 => m_Wrapper.m_GamePlay_SelectCharacter_2;
        public InputAction @SelectCharacter_3 => m_Wrapper.m_GamePlay_SelectCharacter_3;
        public InputAction @SelectCharacter_4 => m_Wrapper.m_GamePlay_SelectCharacter_4;
        public InputAction @RightClick => m_Wrapper.m_GamePlay_RightClick;
        public InputAction @LeftClick => m_Wrapper.m_GamePlay_LeftClick;
        public InputAction @Esc => m_Wrapper.m_GamePlay_Esc;
        public InputAction @Del => m_Wrapper.m_GamePlay_Del;
        public InputAction @PullUp => m_Wrapper.m_GamePlay_PullUp;
        public InputAction @PullDown => m_Wrapper.m_GamePlay_PullDown;
        public InputAction @Brake => m_Wrapper.m_GamePlay_Brake;
        public InputAction @Load => m_Wrapper.m_GamePlay_Load;
        public InputAction @PushCar => m_Wrapper.m_GamePlay_PushCar;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void AddCallbacks(IGamePlayActions instance)
        {
            if (instance == null || m_Wrapper.m_GamePlayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Add(instance);
            @SelectCharacter_1.started += instance.OnSelectCharacter_1;
            @SelectCharacter_1.performed += instance.OnSelectCharacter_1;
            @SelectCharacter_1.canceled += instance.OnSelectCharacter_1;
            @SelectCharacter_2.started += instance.OnSelectCharacter_2;
            @SelectCharacter_2.performed += instance.OnSelectCharacter_2;
            @SelectCharacter_2.canceled += instance.OnSelectCharacter_2;
            @SelectCharacter_3.started += instance.OnSelectCharacter_3;
            @SelectCharacter_3.performed += instance.OnSelectCharacter_3;
            @SelectCharacter_3.canceled += instance.OnSelectCharacter_3;
            @SelectCharacter_4.started += instance.OnSelectCharacter_4;
            @SelectCharacter_4.performed += instance.OnSelectCharacter_4;
            @SelectCharacter_4.canceled += instance.OnSelectCharacter_4;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @Esc.started += instance.OnEsc;
            @Esc.performed += instance.OnEsc;
            @Esc.canceled += instance.OnEsc;
            @Del.started += instance.OnDel;
            @Del.performed += instance.OnDel;
            @Del.canceled += instance.OnDel;
            @PullUp.started += instance.OnPullUp;
            @PullUp.performed += instance.OnPullUp;
            @PullUp.canceled += instance.OnPullUp;
            @PullDown.started += instance.OnPullDown;
            @PullDown.performed += instance.OnPullDown;
            @PullDown.canceled += instance.OnPullDown;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @Load.started += instance.OnLoad;
            @Load.performed += instance.OnLoad;
            @Load.canceled += instance.OnLoad;
            @PushCar.started += instance.OnPushCar;
            @PushCar.performed += instance.OnPushCar;
            @PushCar.canceled += instance.OnPushCar;
        }

        private void UnregisterCallbacks(IGamePlayActions instance)
        {
            @SelectCharacter_1.started -= instance.OnSelectCharacter_1;
            @SelectCharacter_1.performed -= instance.OnSelectCharacter_1;
            @SelectCharacter_1.canceled -= instance.OnSelectCharacter_1;
            @SelectCharacter_2.started -= instance.OnSelectCharacter_2;
            @SelectCharacter_2.performed -= instance.OnSelectCharacter_2;
            @SelectCharacter_2.canceled -= instance.OnSelectCharacter_2;
            @SelectCharacter_3.started -= instance.OnSelectCharacter_3;
            @SelectCharacter_3.performed -= instance.OnSelectCharacter_3;
            @SelectCharacter_3.canceled -= instance.OnSelectCharacter_3;
            @SelectCharacter_4.started -= instance.OnSelectCharacter_4;
            @SelectCharacter_4.performed -= instance.OnSelectCharacter_4;
            @SelectCharacter_4.canceled -= instance.OnSelectCharacter_4;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @Esc.started -= instance.OnEsc;
            @Esc.performed -= instance.OnEsc;
            @Esc.canceled -= instance.OnEsc;
            @Del.started -= instance.OnDel;
            @Del.performed -= instance.OnDel;
            @Del.canceled -= instance.OnDel;
            @PullUp.started -= instance.OnPullUp;
            @PullUp.performed -= instance.OnPullUp;
            @PullUp.canceled -= instance.OnPullUp;
            @PullDown.started -= instance.OnPullDown;
            @PullDown.performed -= instance.OnPullDown;
            @PullDown.canceled -= instance.OnPullDown;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @Load.started -= instance.OnLoad;
            @Load.performed -= instance.OnLoad;
            @Load.canceled -= instance.OnLoad;
            @PushCar.started -= instance.OnPushCar;
            @PushCar.performed -= instance.OnPushCar;
            @PushCar.canceled -= instance.OnPushCar;
        }

        public void RemoveCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamePlayActions instance)
        {
            foreach (var item in m_Wrapper.m_GamePlayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);
    public interface IGamePlayActions
    {
        void OnSelectCharacter_1(InputAction.CallbackContext context);
        void OnSelectCharacter_2(InputAction.CallbackContext context);
        void OnSelectCharacter_3(InputAction.CallbackContext context);
        void OnSelectCharacter_4(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
        void OnDel(InputAction.CallbackContext context);
        void OnPullUp(InputAction.CallbackContext context);
        void OnPullDown(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnLoad(InputAction.CallbackContext context);
        void OnPushCar(InputAction.CallbackContext context);
    }
}
